### ISSUE TITLE
Configuration LDAP posixGroup

### ISSUE THREAD

**Issue by acidjames** [EsupPortail/esup-pay#1]
Bonjour,

j'ai un souci concernant la configuration LDAP et l'autorisation de base. Je ne suis pas un grand expert de LDAP mais nous disposons bien d'un schema Supann.

Par exemple, si je veux autoriser tous les employés à administrer l'appli (ce ne sera pas le cas), voici ce que je teste sans succès : 

esup-pay.properties
```
# for posixGroup set memberUid={1} but for groupOfNames set member={0}
ldap.groupSearchFilter=memberUid={1}
ldap.groupAdmin=eduPersonAffiliation={employee}

```

posixGroup = on retrouve cette config sur openldap ? L'autre est pour ActiveDirectory de ce que j'ai compris ?

En vous remerciant,

**Comment by vbonamy** [comment]
Bonjour,
Esup-Pay attendait véritablement un posixGroup ou groupOfNames et non un filtre ldap comme vous le proposiez ici.
Aussi, suite à votre retour,  Esup-Pay propose en 1.1.0 (disponible aujourd'hui même) cette possibilité : 
dans esup-pay.properties vous avez maintenant la possibilité de mettre, par rapport à votre exemple : ldap.groupAdminFilter=eduPersonAffiliation=employee
Bien cordialement.
