### ISSUE TITLE
problème avec callback paybox

### ISSUE THREAD

**Issue by lbouquinUniv** [EsupPortail/esup-pay#12]
Bonjour,
la transaction est bien enregistrer mais il y a un problème avec le call back de paybox. Aucune information dans l'onglet  transaction et statistiques. 
Auriez vous une idée d'où proviendrais cette erreur. aucun message d'erreur niveau postgress et niveau tomcat

Cordialement, 
Laurent

**Comment by vbonamy** [comment]
Bonjour,
Une question / réponse dans la FAQ correspond à cette issue, cf ci-dessous, aussi je me permets de clore l'issue github ici.
[Le paiement sur Paybox a été effectué mais la transaction n'apparait pas dans la liste des Transactions sur l'interface.](https://www.esup-portail.org/wiki/display/ESUPPAY/FAQ#FAQ-LepaiementsurPayboxa%C3%A9t%C3%A9effectu%C3%A9maislatransactionn'apparaitpasdanslalistedesTransactionssurl'interface.)
Cordialement,
Vincent
