### ISSUE TITLE
Postgresql / pom.xml

### ISSUE THREAD

**Issue by devwald** [EsupPortail/esup-pay#2]
Bonjour,

Pour information, sur la version 1.1.0 en exécutant un mvn package, je restais bloqué sur : 

```
[INFO] ------------------------------------------------------------------------
[INFO] Building esup-pay 1.1.0
[INFO] ------------------------------------------------------------------------
Downloading: http://maven.springframework.org/release/org/postgresql/postgresql/42.1.4/postgresql-42.1.4.pom
```

J'ai donc changé mon pom.xml la partie postgresql avec une ancienne version : 

```
<groupId>postgresql</groupId>
<artifactId>postgresql</artifactId>
<version>9.1-901-1.jdbc4</version>
```

Cdt.

**Comment by vbonamy** [comment]
Bonjour,
J'ai retesté et postgresql-42.1.4 est bien disponible dans le maven
central, peut-être un pb réseau ou similaire temporaire ici lors du mvn
package ?
Bien cordialement,
Vincent Bonamy.

2018-06-21 13:44 GMT+02:00 devwald <notifications@github.com>:

**Comment by devwald** [comment]
Bizarre, j'ai donc remis : 
```
                        <groupId>org.postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <version>42.1.4</version>
```
Et je reste toujours bloqué sur : 

```
[INFO] ------------------------------------------------------------------------
[INFO] Building esup-pay 1.1.0
[INFO] ------------------------------------------------------------------------
Downloading: http://maven.springframework.org/release/org/postgresql/postgresql/42.1.4/postgresql-42.1.4.pom
```
Alors qu'avec une ancienne version de Postgres (cf. mon message initial), je n'ai pas de soucis.

Pour info quand on va sur l'URL : http://maven.springframework.org/release/org/postgresql/postgresql/42.1.4/postgresql-42.1.4.pom on obtient une page indiquant ceci : 

```
  |  
-- | --
errors |  
0 |  
status | 404
message | "Could not find resource"
```

**Comment by vbonamy** [comment]
En fait cette dépendance est donnée directement par le maven central (et
non par le maven spring) ;
voir :
https://mvnrepository.com/artifact/org.postgresql/postgresql/42.1.4
-> http://central.maven.org/maven2/org/postgresql/
postgresql/42.1.4/postgresql-42.1.4.pom est ok par exemple.

C'est peut-être votre .m2 qui pose problème ... quitte à modifier la
version, mettez plutôt une version plus récente éventuellement (pour faire
face à l'issue #3 ) ; la 42.2.2 par exemple.

Vincent.

**Comment by devwald** [comment]
C'est corrigé.
J'ai téléchargé directement le .jar (https://jdbc.postgresql.org/download/postgresql-42.1.4.jar
) et je l'ai positionné dans le WEB-INF/lib

Merci pour votre aide.
