### ISSUE TITLE
Erreur sur colonne "managers_email" lors de la création d'un nouvel évènement

### ISSUE THREAD

**Issue by XB35000** [EsupPortail/esup-pay#38]
Bonjour,

Lorsque je souhaite créer un nouvel évènement j'ai systématiquement l'erreur suivante : 

"Data access failure

Problème d'accès à la base de données."

Les logs m'indiquent une erreur sur la colonne "managers_email' : 

    [[2024-02-02 11](callto:2024-02-02 11):06:12] [info] [2024-02-02 11](callto:2024-02-02 11):06:12,513 [ajp-nio-[127.0.0.1-8009](callto:127.0.0.1-8009)-exec-1] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - ERROR: null value in column "managers_email" violates not-null constraint

    Pourtant j'indique bien des adresses mails dans le champ "managers_email".

Avez-vous une solution à m'apporter ?

Merci et bonne journée.

**Comment by vbonamy** [comment]
Bonjour,

La colonne managers_email de la table esuppay n'est plus utilisée depuis la version 1.5.0 de janvier 2022.

Peut-être avez-vous fait une mise à jour depuis une version antérieure sans passer le script sql https://github.com/EsupPortail/esup-pay/blob/master/src/etc/upgrade-1.5.sql ?

Cf https://www.esup-portail.org/wiki/display/ESUPPAY#ESUPPAY-Changelog

Bonne soirée,
Vincent.
