### ISSUE TITLE
Configuration LDAP

### ISSUE THREAD

**Issue by daividh** [EsupPortail/esup-pay#5]
Bonjour,

Petit soucis ou incompréhension au sujet de la configuration LDAP.

J'ai la configuration suivante:
```
ldap.peopleSearchBase=ou=people
ldap.peopleSearchFilter=(uid={0})
ldap.groupSearchBase=ou=groups
ldap.groupSearchFilter=member={0}
ldap.groupAdmin=H_138
```

De ce que j'ai compris du process : 
- Après l'authentification CAS, une requête LDAP est faite pour récupérer le dn de la personne connectée
- Ce dn est utilisé pour faire une recherche sur la branche des groupes pour récupérer le cn des groupes auquel fait parti l'utilisateur.
- Si dans ces groupes, ldap.groupAdmin (H_138 dans mon cas) = un cn retourné précédemment, alors l'utilisateur est considéré comme étant admin de l'application.

Et-ce bien cela ?

Si oui, dans mon cas cela ne fonctionne pas. Je n'arrive pas à accéder à la page d'admin. "Vous n'êtes pas autorisé à consulter cette page".

```
INFO  PayLdapAuthoritiesPopulator  - Roles from ldap groups for xxxxxx : [ROLE_ADMINXXXX, ROLE_ADMINH_138]
DEBUG PayLdapAuthoritiesPopulator  - Group from LDAP : ADMINH_138
[...]
DEBUG AbstractSecurityInterceptor  - Secure object: FilterInvocation: URL: /admin; Attributes: [hasRole('ROLE_ADMIN') or hasRole('ROLE_MANAGER') or hasRole('ROLE_VIEWER')]
[...]
DEBUG AbstractSecurityInterceptor  - Previously Authenticated: org.springframework.security.cas.authentication.CasAuthenticationToken@d89a4f74: Principal: org.springframework.security.ldap.userdetails.LdapUserDetailsImpl@2bf064be: Dn: uid=XXXXX,ou=people,dc=univ-ubs,dc=fr; Username: XXXX; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; CredentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMINXXXX, ROLE_ADMINH_138; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@7798: RemoteIpAddress: 172.17.34.63; SessionId: 22C5FD341668A0561D2B0C27F5518B88; Granted Authorities: ROLE_ADMINXXXX, ROLE_ADMINH_138 Assertion: org.jasig.cas.client.validation.AssertionImpl@132d9f8a Credentials (Service/Proxy Ticket): ST-778-dsF-avbRpDV-slTSaQo
```

Je comprend que l'accès est refusé car je n'ai pas le rôle ROLE_ADMIN, mais je ne comprend pas pourquoi je ne l'obtiens pas.

Merci pour l'aide.

**Comment by vbonamy** [comment]
Bonjour,
A priori votre configuration devrait être
```
ldap.groupAdmin=ADMINH_138
```
au lieu de 
```
ldap.groupAdmin=H_138
```
non ?
Vincent.

**Comment by daividh** [comment]
Merci pour ta réponse Vincent.

J'avoue être confu et ne pas comprendre.
J'avais testé H_138, ADMINH_138, ROLE_ADMINH_138, je pense qu'il y a eu un soucis car aucun de ces 3 ne fonctionnait.
Suite à ton message, je reteste ADMINH_138, et là, ça fonctionne...

Je vais surement  faire une PR pour alimenter la doc si tu le veux bien.

Désolé pour le dérangement

**Comment by vbonamy** [comment]
Pas de problème.
Cf une autre issue #1 cette partie mériterait peut-être bien une documentation encore plus claire, dans la conf ou plutôt dans le wiki esup en fait alors ?
Aussi, tu avais vu le passage là-dessus dans la FAQ ?
https://www.esup-portail.org/wiki/display/ESUPPAY/FAQ
L'histoire de ROLE_ ajouté aux noms des groupes ldap provient du paramétrage par défaut de spring security en fait - cf le fichier descripteur spring global là-dessus : applicationContext-security.xml
A+
